#!/usr/bin/env bash
#
# you would think that "env python" would work just as well in every case, but you'd be wrong
#
python -c"from IPython import Shell; Shell.IPShellEmbed(argv=['-rcfile=~/.ipython/msh.rc'])()"
