#!/usr/bin/env bash
#
# prints git branch for wd to stdout, or "(unknown)" if not possible
#
function find_git_branch {
    local dir=. head
    until [ "$dir" -ef / ]; do
        if [ -f "$dir/.git/HEAD" ]; then
            head=$(< "$dir/.git/HEAD")
            if [[ $head == ref:\ refs/heads/* ]]; then
                echo "${head#*/*/}"
            elif [[ $head != '' ]]; then
                echo '(detached)'
            else
                echo '(unknown)'
            fi

        fi
        dir="../$dir"
    done
}

find_git_branch
