#!/usr/bin/env python
#
# you would think that "env python" would work everywhere, but due
# due to interaction with sourced venv's this is actually a tricky
# business.  is it possible for this shell to for activating multiple
# venv's potentially using multiple python versions?
#
import sys

MSH_RC = '~/.ipython/smash/config/smash.rc'

def main():
    print "bootstrapping smart-shell from $MSH_RC"
    Shell.IPShellEmbed(argv=['-rcfile={0}'.format(MSH_RC)])()

if __name__=='__main__':
    try:
        from IPython import Shell
    except:
        print 'FATAL: cannot run smash: system ipython is not available'
        print
        sys.exit(1)
    else:
        main()
