#!/usr/bin/env python
#
# you would think that "env python" would work everywhere, but due
# due to interaction with sourced venv's this is actually a tricky
# business..

def main():
    """ essentially this is like calling smashlib.util.embed(), but,
        we might not actually be able to import smashlib yet.
    """
    import os, sys
    _smashlib, _smashplugins = (os.path.expanduser('~/.smash/'),
                                os.path.expanduser('~/.smash/plugins'))
    for p in [_smashlib,_smashplugins]:
        if p not in sys.path:
            sys.path.append(p)
    import smashlib
    from smashlib.embed import SmashEmbed
    SmashEmbed()()

if __name__=='__main__':
    try:
        from IPython import Shell
    except:
        print ("\nFATAL: cannot run SmaSh.\n"
               "  IPython lib is not available.  \n"
               "    To reproduce this error, try running:\n"
               "      /usr/bin/env python -c\"from IPython import Shell\"\n")
        sys.exit(1)
    else:
        main()
