#!/usr/bin/python
#
# you would think that "env python" would work just as well in every case, but you'd be wrong
#

MSH_RC = '~/.ipython/smash/smash.rc'
print "bootstrapping smart-shell from $MSH_RC"
from IPython import Shell
class ABC(Shell.IPShellEmbed):
    def __init__(self, *args, **kargs):
        #try:
        Shell.IPShellEmbed.__init__(self, *args, **kargs)
        #except:
        #  print 'busted!'
        #  from IPython import Shell; Shell.IPShellEmbed(argv=['-noconfirm_exit'])()
ABC(argv=['-rcfile={0}'.format(MSH_RC)])() #" $@
