site_name: smash
theme_dir: glsh
site_dir: site
docs_dir: docs
repo_url: https://github.com/mattvonrocketstein/smashlib.git
site_author: mvr
pages:
- 'Home': 'index.md'
- 'Feature Overview': 'features.md'
- 'Configuration': 'configuration.md'
- 'Plugins':
  - 'Autojump': 'smash_plugins/prompt.md'
  - 'Python: Tools completion': 'smash_plugins/python_tools_completion.md'
  - 'Python: Virtualenv': 'smash_plugins/venv.md'
  - 'Prompt': 'smash_plugins/prompt.md'
  - 'CD Hooks': 'smash_plugins/cd_hooks.md'
  - 'Do what I Mean': 'smash_plugins/dwim.md'
  - 'Enhanced "which"': 'smash_plugins/which.md'
  - 'Writing new plugins': 'smash_plugins/dev.md'
#- 'Python Features': 'python_use_cases.md'
#- 'Shell Features': 'shell_use_cases.md'
- 'Project Manager': 'project_manager.md'
- 'API Reference': 'api/index.html'
extra:
    base_url: '/'
