site_name: smash
theme_dir: glsh
site_dir: site
docs_dir: docs
repo_url: https://github.com/mattvonrocketstein/smashlib.git
site_author: mvr
pages:
- 'Home': 'index.md'
- 'Feature Overview': 'features.md'
- 'Configuration': 'configuration.md'
- 'Plugins':
  - 'old': 'smash_plugins/index.md'
  - 'prompt': 'smash_plugins/prompt.md'
#- 'Python Features': 'python_use_cases.md'
#- 'Shell Features': 'shell_use_cases.md'
- 'Project Manager': 'project_manager.md'
- 'API Reference': 'api/index.html'
extra:
    base_url: '/'
